Add new overtime hours field
AY2324S1-CS2103T-W12-1/tp pull request #116
Opened 2023-10-22 09:45 UTC by JasonRay168

2023-10-22 10:08 UTC, miljyy requested changes

2023-10-22 10:08 UTC, miljyy commented on src/test/java/seedu/address/model/employee/EmployeeTest.java
> +                + ", departments=" + ALICE.getDepartments() + ", overtime hours=" + ALICE.getOvertimeHours() + "}";
I believe that employee ALICE does not have the attribute overtime hours? You need to update the employees in the relevant files in the testutil folder.

2023-10-22 12:29 UTC, inezkok requested changes
I think you might have missed out on some files:
- SampleDataUtil.java (add in the overtime attribute to the sample data)
- JsonAdaptedEmployee.java (add in the overtime attribute to the json creater and constructor)
- EmployeeCard.java and EmployeeListCard.fxml (edit the employee fxml card to show overtime attribute in GUI)

You can refer to [this PR](https://github.com/AY2324S1-CS2103T-W12-1/tp/pull/92/files#diff-d53718fbb99fe3f9a3ea54d9b6f8ce6cd7060fe64b15d8855a8de55c5ef5de52) for the files changed (just ignore the Command changes)

2023-10-23 07:12 UTC, inezkok approved these changes
overall looks good to me might need to add more test cases to fix the code coverage issue but other than that well done!

2023-10-23 07:12 UTC, inezkok commented on src/main/java/seedu/address/model/employee/OvertimeHours.java
> +    public static final String MESSAGE_CONSTRAINTS = "Number of overtime hours left"
I think it could be re-phrased to "Number of overtime hours should not exceed 72 or be below 0"? (number of overtime hours left can be misleading, cause it sounds like an employee can work for more than 72 overtime hours)

2023-10-23 07:16 UTC, miljyy approved these changes

2023-10-23 07:18 UTC, merged